# Default values for microservice-template
# This is a YAML-formatted file.

# Service configuration
service:
  name: microservice
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Image configuration
image:
  repository: acrrevaiprod.azurecr.io/microservice
  tag: latest
  pullPolicy: IfNotPresent

# Deployment configuration
deployment:
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

# Resource configuration
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Environment configuration
environment: staging

# Environment variables
env:
  - name: ENVIRONMENT
    value: "{{ .Values.environment }}"
  - name: LOG_LEVEL
    value: "info"
  - name: PORT
    value: "8080"

# Health check configuration
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness check configuration
readinessCheck:
  enabled: true
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Service account configuration
serviceAccount:
  create: true
  name: ""
  annotations: {}

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: microservice.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Network Policy
networkPolicy:
  enabled: false

# Service Monitor for Prometheus
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s

# Labels and annotations
labels: {}
annotations: {}

# Pod labels and annotations
podLabels: {}
podAnnotations: {}
